# Generated by Django 5.0.3 on 2024-03-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0012_alter_women_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/% Y/% m/% d/', verbose_name='Fotografiya'),
        ),
    ]
